### ISSUE TITLE
crUd broken

### ISSUE THREAD

**Issue by halfk1ng** [SinghDigamber/vue-mevn-stack-app#24]
Upon trying to edit first test entry to the CRUD interface, does not allow an append. UI stays static, terminal output:

createError is not defined
(node:41486) DeprecationWarning: Mongoose: `findOneAndUpdate()` and `findOneAndDelete()` without the `useFindAndModify` option set to false are deprecated. See: https://mongoosejs.com/docs/deprecations.html#findandmodify

**Comment by losfroger** [comment]
This is a small error in the index.js inside the backend. You need to add the following line:
`const createError = require('http-errors');` below the `const bodyParser`
